name: Java CI with Maven

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Update pom.xml
      run: mvn versions:set -DnewVersion=1.0.1

    - name: Create Pull Request
      run: |
        TOKEN="${{ secrets.GITHUB_TOKEN }}"
        REPO="${{ github.repository }}"
        BRANCH="${{ github.ref }}"
        curl -X POST -H "Authorization: token $TOKEN" -d "{\"title\":\"Automated Pull Request\",\"head\":\"$BRANCH\",\"base\":\"master\",\"body\":\"All checks have passed. This pull request is ready to be merged.\"}" "https://api.github.com/repos/$REPO/pulls"

    - name: Run tests
      run: mvn -B test --file pom.xml

    - name: Generate Test Reports
      run: mvn surefire-report:report 
      
